# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chickenapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chickenapp123.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fc7298d2eb3d4393bacd71efe7ff2d11 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b661736abb974dbd9653048c90451f44 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chickenapp123.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fc7298d2eb3d4393bacd71efe7ff2d11 }}/chicken:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chickenapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e5b82cefbb9c4627b6087281799e5b56 }}
        images: 'chickenapp123.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fc7298d2eb3d4393bacd71efe7ff2d11 }}/chicken:${{ github.sha }}'